# Generated by Django 2.1.2 on 2018-11-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent',
            new_name='draft',
        ),
    ]
